Update config

diff --git a/.github/config b/.github/config
--- a/.github/config
+++ b/.github/config
@@ -24,6 +24,16 @@ rm -rf package/lean/luci-app-ttyd
 ./scripts/feeds update -a
 ./scripts/feeds install -a
 
+git clone https://github.com/tuanqing/lede-mod
+
+echo "patching feeds luci"
+git apply lede-mod/luci/*.patch --directory=feeds/luci
+[ $? = 0 ] || echo "failed"
+
+echo "patching luci-theme-bootstrap-mod"
+git apply lede-mod/bootstrap/*.patch --directory=package/luci-theme-bootstrap-mod
+[ $? = 0 ] || echo "failed"
+
 zzz="package/lean/default-settings/files/zzz-default-settings"
 
 sed -i 's/samba/samba4/' $zzz
@@ -63,6 +73,7 @@ CONFIG_PACKAGE_luci-theme-bootstrap-mod=y
 # CONFIG_UnblockNeteaseMusic_NodeJS is not set
 ## others
 CONFIG_BRCMFMAC_SDIO=y
+CONFIG_LUCI_LANG_en=y
 EOF
 
 make defconfig
